### ISSUE TITLE
ACE Löscht Items

### ISSUE THREAD

**Issue by br1zey** [A3ReallifeRPG/ReallifeRPG4.4#14]
Item Shop Sanis ACE Items werden nicht ins Inventar gelegt.
Wenn man verbandkasten kauft und sich dann mit einer binde verbindet sind alle Items weg

**Comment by vabene1111** [comment]
item löschen gefixt, shops müssen noch

**Comment by vabene1111** [comment]
auch items kaufen behoben (fix war in 4.0)
